[workspace]
authors = ["BatuhanGQskt <e231529@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
name = "chemtensor_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
vector = ">=1.7.0,<2"
time = ">=1.9,<2"
max = ">=25.7.0.dev2025111305,<26"
